version: '3'

services:
    db:
        image: postgres:16-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
        ports:
            - '5432:5432'
        volumes:
            - postgres13:/var/lib/postgresql/data
        networks:
            - myapp_net
    redis:
        image: redis:7.0.15-alpine
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data
        networks:
            - myapp_net
    web:
        build: .
        command: bundle exec rails server 
        ports:
            - '3000:3000'
        volumes:
            - .:/rails
        depends_on:
            - db
            - redis
        environment:
            - DATABASE_URL=postgresql://postgres:password@db:5432/myapp
            - REDIS_URL=redis://redis:6379/0
        networks:
            - myapp_net
    sidekiq:
        build: .
        command: bundle exec sidekiq
        volumes:
            - .:/rails
        depends_on:
            - db
            - redis
        environment:
            - DATABASE_URL=postgresql://postgres:password@db:5432/myapp
            - REDIS_URL=redis://redis:6379/0
        networks:
            - myapp_net
    test:
        build: .
        command: bundle exec rspec
        volumes:
            - .:/rails
        depends_on:
            - db
            - redis
        environment:
            - DATABASE_URL=postgresql://postgres:password@db:5432/myapp_test
            - REDIS_URL=redis://redis:6379/0
        networks:
            - myapp_net
volumes:
    postgres13:
    redis_data:
networks:
    myapp_net:
